apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3   # Initial number of replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          resources:
            requests:
              memory: "15Mi"
              cpu: "1m"
            limits:
              memory: "20Mi"
              cpu: "2m"
          ports:
            - containerPort: 80
